name: Repository Dispatch
on:
  repository_dispatch:
    types: [new-image]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ github.event.client_payload.image }}

  
