name: Repository Dispatch
on:
  repository_dispatch:
    types: [new-image]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update deployment.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'dev/deployment.yaml'
          propertyPath: 'spec.template.spec.containers.image.value'
          value: ${{ github.event.client_payload.image }}
          commitChange: true
          updateFile: true

  