name: Repository Dispatch
on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'dev/deployment.yaml'
      env:
        image: ${{ github.event.client_payload.image }}

  