name: Repository Dispatch
on:
  workflow_dispatch:
#on:
#  repository_dispatch:
#    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Image Version
      uses: mikefarah/yq@master
      with:
        #cmd: yq e -i 'spec.template.spec.containers[0].image.value = "${{ github.event.client_payload.image }}"' dev/deployment.yaml 
        cmd: yq w dev/deployment.yaml 'spec.template.spec.containers[0].image' 'test' 